### ISSUE TITLE
trening: przypisanie funkcjonalności do interfejsu

### ISSUE THREAD

**Issue by jbiegun14** [TakiPrzemo/WhosThere#1]
Przypisanie do elementów graficznych odpowiadających im funkcji

Problemy:
Nie wiem jak to zrobić - w pliku trening i jego uruchamianiu nie ma elementów graficznych, przynajmniej tak mi się wydaje.

**Comment by konpferd** [comment]
Celem jest zrobienie interfejsu z dużym przyciskiem do wykonania pliku .yml i wyświetlanie informacji o pomyślnym (lub nie) zakończeniu zadania w postaci tekstu w oknie lub messageboxa

**Comment by jbiegun14** [comment]
08.06.2024r. 30min
Zrobiono:
Stworzono okno z przyciskiem tworzącym wymagany plik.
Okno przed zamknięciem informuje czy twarz została poprawnie dodana do katalogu.
